### ISSUE TITLE
JnuTongManagementPage

### ISSUE THREAD

**Issue by Songseunghyo1** [Songseunghyo1/PortalServiceProject#1]
# Jnu-tong Management Page
--------

- [x] 로그인화면 입력 양식 화면 정 가운데로 배치
- [x] 로그인할 때  DB에 저장된 데이터를 이용하여 인가된 사용자인지 판단하기
- [x] 데이터 표현 방식 구상하기
- [x] Thymeleaf 이용해서 DB로부터 테스트데이터 가져오기  
- [x]  Thymeleaf 적용하여 전체 데이터 긁어오기
- [x] 학사일정 데이터베이스에서 가져오기
- [x] 학사일정 수정페이지
- [x] 모든 페이지를 콤보박스가 아닌 하이퍼링크로 문서를 연결하는 방식으로 구현
--------
## Todo
~~- [ ] /bus_one page에서 선택된 콤보박스를 기반으로 필터링~~
~~- [ ] /bus_two page 에서 선택된 콤보박스를 기반으로 필터링~~
- [ ] /bus_one page, /bus_two page 수정기능 삽입

**Comment by Songseunghyo1** [comment]
javascript를 이용하여 변경 또는 html문서를 하이퍼링크로 연결할 것임
